version: 2.1
orbs:
  node: circleci/node@4.1.0

node-version: &node-version "14.15"

workflows:
  node-tests:
    jobs:
      - node/test:
          name: Tests
          pkg-manager: yarn
          version: *node-version
      - node/test:
          name: Lint
          pkg-manager: yarn
          run-command: lint
          version: *node-version
